const $=s=>document.querySelector(s),modal=$('#modal'),feed=$('#feed'),profile=$('#profile');let db,videos=[],tab='home';let settings=JSON.parse(localStorage.getItem('owitokSettings')||'{"autoplay":true,"notifications":true,"privacy":false,"dark":true,"dataSaver":false,"sound":true}'),comments=JSON.parse(localStorage.getItem('owitokComments')||'{}');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('owitokSettings',JSON.stringify(settings));localStorage.setItem('owitokComments',JSON.stringify(comments))}
function initDB(){return new Promise((ok,no)=>{let r=indexedDB.open('OwiTokDB',1);r.onupgradeneeded=e=>e.target.result.createObjectStore('videos',{keyPath:'id'});r.onsuccess=e=>{db=e.target.result;ok()};r.onerror=()=>no(r.error)})}
function all(){return new Promise((ok,no)=>{let r=db.transaction('videos').objectStore('videos').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}function put(v){return new Promise((ok,no)=>{let r=db.transaction('videos','readwrite').objectStore('videos').put(v);r.onsuccess=ok;r.onerror=()=>no(r.error)})}
async function load(){videos=await all();videos.sort((a,b)=>b.createdAt-a.createdAt);videos.forEach(v=>v.src=URL.createObjectURL(v.blob))}
function nav(t){tab=t;document.querySelectorAll('.navItem').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));if(t==='profile')showProfile();else{profile.classList.add('hidden');feed.classList.remove('hidden');render()}}
function render(){feed.innerHTML='';let list=tab==='following'?videos.filter(v=>v.following):videos;list.forEach(v=>{let c=document.createElement('article');c.className='card';c.dataset.id=v.id;c.innerHTML=`<video playsinline preload="metadata"></video><div class="shade"></div><button class="sound">${v.muted?'🔇':'🔊'}</button><div class="info"><div class="user">@${esc(v.username)}</div><div>${esc(v.caption)}</div></div><div class="actions"><button class="act like ${v.liked?'liked':''}"><i>♥</i><span>${v.likes}</span></button><button class="act com"><i>💬</i><span>${(comments[v.id]||[]).length}</span></button><button class="act fol"><i>${v.following?'✓':'＋'}</i><span>${v.following?'Following':'Follow'}</span></button><button class="act share"><i>↗</i><span>Share</span></button></div><div class="pop">♥</div>`;feed.append(c);let vid=c.querySelector('video');vid.src=v.src;vid.muted=v.muted!==false;c.querySelector('.sound').onclick=e=>{e.stopPropagation();v.muted=!v.muted;vid.muted=v.muted;e.currentTarget.textContent=v.muted?'🔇':'🔊';put(v);if(!v.muted)vid.play().catch(()=>{})};c.querySelector('.like').onclick=()=>like(v,c);c.querySelector('.com').onclick=()=>openComments(v);c.querySelector('.fol').onclick=()=>{v.following=!v.following;put(v);render()};c.querySelector('.share').onclick=()=>share();let last=0;vid.addEventListener('touchend',e=>{let n=Date.now();if(n-last<320){e.preventDefault();if(!v.liked)like(v,c,true)}last=n},{passive:false});vid.onclick=()=>vid.paused?vid.play().catch(()=>{}):vid.pause()});observe()}
function like(v,c,pop=false){v.liked=!v.liked;v.likes=Math.max(0,v.likes+(v.liked?1:-1));put(v);let b=c.querySelector('.like');b.classList.toggle('liked',v.liked);b.querySelector('span').textContent=v.likes;if(pop&&v.liked){let p=c.querySelector('.pop');p.classList.remove('show');void p.offsetWidth;p.classList.add('show')}}
function observe(){let o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&settings.autoplay)e.target.play().catch(()=>{});else e.target.pause()}),{threshold:.7});document.querySelectorAll('.card video').forEach(v=>o.observe(v))}
function openCreate(){modal.innerHTML='<div class="backdrop"><div class="sheet"><button class="close">×</button><h2>Create</h2><p>Choose how to add your video.</p><div class="options"><button class="option" id="cam"><b>📹</b>Camera</button><button class="option" id="gal"><b>🖼️</b>Gallery</button></div></div></div>';$('.close').onclick=close;$('#cam').onclick=()=>{$('#camera').click();close()};$('#gal').onclick=()=>{$('#gallery').click();close()}}
async function files(fs){for(let f of fs){if(!f.type.startsWith('video/'))continue;await put({id:crypto.randomUUID(),blob:f,username:'owitok_user',caption:f.name.replace(/\.[^.]+$/,''),likes:0,liked:false,following:false,muted:true,createdAt:Date.now()})}await load();nav('home')}
$('#gallery').onchange=e=>files(e.target.files);$('#camera').onchange=e=>files(e.target.files);
function openComments(v){let cs=comments[v.id]||[];modal.innerHTML=`<div class="backdrop"><div class="sheet"><button class="close">×</button><h2>Comments</h2><div class="commentList">${cs.length?cs.map(x=>`<div class="comment"><b>@${esc(x.user)}</b><br>${esc(x.text)}</div>`).join(''):'<p>No comments yet.</p>'}</div><div class="commentBar"><input id="ct" placeholder="Add a comment"><button class="primary" id="post">Post</button></div></div></div>`;$('.close').onclick=close;$('#post').onclick=()=>{let t=$('#ct').value.trim();if(!t)return;(comments[v.id]??=[]).push({user:'owitok_user',text:t});save();close();render()}}
function openSearch(){modal.innerHTML='<div class="backdrop"><div class="sheet"><button class="close">×</button><h2>Search</h2><input id="q" class="search" placeholder="Search OwiTok"><div id="res"></div></div></div>';$('.close').onclick=close;$('#q').oninput=e=>{$('#res').innerHTML=videos.filter(v=>(v.username+' '+v.caption).toLowerCase().includes(e.target.value.toLowerCase())).map(v=>`<div class="row"><span>@${esc(v.username)} — ${esc(v.caption)}</span><button data-id="${v.id}">Open</button></div>`).join('')||'<p>No results.</p>';$('#res').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{close();nav('home');setTimeout(()=>document.querySelector(`[data-id="${b.dataset.id}"]`)?.scrollIntoView({behavior:'smooth'}),80)})}}
function showProfile(){feed.classList.add('hidden');profile.classList.remove('hidden');let likes=videos.reduce((n,v)=>n+v.likes,0);profile.innerHTML=`<div class="phead"><div class="ptop"><button id="back">‹</button><h2>@owitok_user</h2><button id="pmore">•••</button></div><div class="avatar">O</div><b>OwiTok User</b><div style="color:#bfb2ca">@owitok_user</div><p>Welcome to my OwiTok profile 💜</p><div class="stats"><div><b>${videos.filter(v=>v.following).length}</b><span>Following</span></div><div><b>0</b><span>Followers</span></div><div><b>${likes}</b><span>Likes</span></div></div><div class="pbuttons"><button class="edit">Edit profile</button><button>Share profile</button></div><div class="tabs"><button class="sel">Videos</button><button>Liked</button></div></div><div class="grid">${videos.map(v=>`<button class="tile" data-v="${v.id}"><video muted playsinline src="${v.src}"></video><span>▶ ${v.likes}</span></button>`).join('')}</div>`;$('#back').onclick=()=>nav('home');$('#pmore').onclick=openSettings;profile.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{let id=b.dataset.v;nav('home');setTimeout(()=>document.querySelector(`[data-id="${id}"]`)?.scrollIntoView({behavior:'smooth'}),80)})}
function row(name,key){return `<div class="row"><span>${name}</span>${key?`<button class="switch ${settings[key]?'on':''}" data-k="${key}"></button>`:'<button>›</button>'}</div>`}
function openSettings(){modal.innerHTML=`<div class="backdrop"><div class="sheet"><button class="close">×</button><h2>Settings and privacy</h2>${row('Account')}${row('Notifications','notifications')}${row('Privacy','privacy')}${row('Security')}${row('Playback','autoplay')}${row('Content preferences')}${row('Language')}${row('Dark mode','dark')}${row('Data Saver','dataSaver')}${row('Sound settings','sound')}${row('Blocked accounts')}${row('Liked videos')}${row('Downloads')}${row('About OwiTok')}${row('Log out')}</div></div>`;$('.close').onclick=close;modal.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{settings[b.dataset.k]=!settings[b.dataset.k];save();openSettings()})}
function openInbox(){modal.innerHTML='<div class="backdrop"><div class="sheet"><button class="close">×</button><h2>Inbox</h2><p>No new notifications.</p></div></div>';$('.close').onclick=close}function close(){modal.innerHTML=''}function share(){if(navigator.share)navigator.share({title:'OwiTok',url:location.href}).catch(()=>{});else navigator.clipboard?.writeText(location.href)}
$('#createBtn').onclick=openCreate;$('#searchBtn').onclick=openSearch;$('#moreBtn').onclick=openSettings;$('#brand').onclick=()=>nav('home');document.querySelectorAll('.navItem').forEach(b=>b.onclick=()=>nav(b.dataset.tab));let sx=0;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>90){if(dx<0)nav('profile');else nav('home')}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');(async()=>{await initDB();await load();render()})();
